### PR TITLE
Swap -moz- prefix for unprefixed animations

### PR DESCRIPTION
**Pull request by i-like-robots**
The `-moz-` prefix for the animation property and `@keyframe` declarations are not required and support for the unprefixed versions is very good: http://caniuse.com/#feat=css-animation

### CODE REVIEW

**Comment by tylergaw** [comment]
@i-like-robots Cool. One small change. The CSS file is generated using Sass. Can you make the changes in the `scss` https://github.com/i-like-robots/css-shaky-animation/blob/master/css/scss/shaky-animation.scss. There are a couple mixins that would need updated.

**Comment by i-like-robots** [comment]
Darn it! In too much of a rush to have paid proper attention.

**Comment by i-like-robots** [comment]
Done and done :blush:

**Comment by i-like-robots** [comment]
Fixed.

**Comment by tylergaw** [comment]
@i-like-robots Thanks man, merged. It's great that we're getting to a point that we can remove these prefixes.

**Pull request merged**
